# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "13:00" #UTC time that translates to 6am phoenix (MST, which is UTC-7)
    open-pull-requests-limit: 5
    labels:
      -"security-update" #label to be given to each pr
