# This is a basic workflow to help execute a test suite located in a different repository

name: CI Test Suite A

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types: [test_result]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Triggers the test suite repository through CURL command
      - name: Trigger Cypress Test Suite A
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/pabloZenledger/cypress_cicd/actions/workflows/testa.yml/dispatches \
          -d '{"ref":"main"}'
      - name: Handle test result
        run: |
          if[["${{ github.event.client_payload.result}}" == "All specs passed!"]]; then
            echo "Tests Passed!"
            #Do something based on success??
          else
            echo "Tests Failed!"
            #Do something based on success??
          fi
